version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/backend/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - postgres_db
  
  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=articles_dev

volumes:
  postgres_data:
