version: '3.8'

services:
  backend:
    build: ./backend
    command: bash scripts/deploy.sh
    volumes:
      - ./backend/:/usr/backend/
    ports:
      - 8000:8000
    env_file:
      - ./backend/article_api/.env.dev
    depends_on:
      - postgres_db
  
  frontend:
    build: ./frontend/article_admin
    command: bash src/scripts/deploy.sh
    volumes:
      - ./frontend/:/usr/frontend
    ports:
      - 3000:3000
    env_file:
      - ./frontend/article_admin/.env
  
  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=django_dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=articles_dev
