# Generated by Django 5.0.4 on 2024-04-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('job_description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'news_categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('superadmin', 'Superadmin')], max_length=10)),
                ('token', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=3000)),
                ('published', models.BooleanField(default=False)),
                ('published_date', models.DateField()),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='article_api.author')),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='article_api.newscategory')),
            ],
        ),
    ]
