# Generated by Django 5.0.4 on 2024-05-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0003_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autho_id', to='article_api.author'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='article_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='article_api.newscategory'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
