# Generated by Django 5.0.4 on 2024-05-04 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_api', '0006_alter_newsarticle_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='article_api.author'),
        ),
    ]
